### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by glebfox** [ilushaaa/jmix-hw-working-with-data#1]
`CarStatsService#calculateCarStatusAsString`: 

1. Pay attention to idea warning about incorrect usage of `StringBuilder`
2. either use `@Nullable` to indicate that null can be passed as a parameter or make `calculateCars` track selection

----

`CarBrowse#onCarsTableMarkAsSold` - it's better to replace item in the container after we manually saved entity. If youed entity  add `Versioned` trait, you'll see that saved entity and the one in the container have different version.

**Comment by ilushaaa** [comment]
fixed
